### ISSUE TITLE
Hi! I would like to increase the image height and width. I tried with changing the const size but it didn't change the image size. Would you please help me?

### ISSUE THREAD

**Issue by saddam-94** [chiddianozie/download_street_view_images#1]

**Comment by chiddianozie** [comment]
Hi there, 
in the variable `skeleton`, the parameter values `size=640x640` refers to the width and height of the image, you can change this to whichever values you prefer. Please let me know if that helps.
Thanks!

**Comment by saddam-94** [comment]
@sirchidi Thank you so much for your immediate  response. I tried according to your instruction but It didn't work. It always generates 640x640. It works also in decreasing size but not grater than mentioned fixed size?

**Comment by chiddianozie** [comment]
Hi there, yeah the max size is 640x640 with the free service. Please, see this [link](https://developers.google.com/maps/documentation/streetview/usage-and-billing). (also, see the screenshot below) Depending on your need, you can use the premium service (via the link) or upscale the size of the image using an editing software. I hope that helps.
<img width="879" alt="Screenshot 2019-12-28 at 19 14 46" src="https://user-images.githubusercontent.com/16417008/71548469-68ee9e80-29a6-11ea-9be8-6c89e0281373.png">

**Comment by saddam-94** [comment]
@sirchidi thank you so much sir for your cordial response :) . I also thought about that 640x640 for free.
